/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Admin.Mahasiswa;

import javax.swing.table.DefaultTableModel;
import java.sql.*;
import Config.DatabaseConnection;
import javax.swing.JOptionPane;
import Config.RandomNim;
import Config.HashUtil;

/**
 *
 * @author muhrobby
 */
public class FormMahasiswa extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormMahasiswa.class.getName());
    public String nim,nama, prodi, no_hp, email;
    public int semester;
    private String nimUSer;
    /**
     * Creates new form FormMahasiswa
     */
    public FormMahasiswa(java.awt.Frame parent, boolean modal, String nim) {
        super(parent, modal);
        initComponents();
        this.nimUSer = nim;
        tampilDataMahasiswa();
    }
//    
//    public void clearForm(){
//                txtNama.setText("");
//                comboProdi.setSelectedIndex(-1);
//                comboSemester.setSelectedIndex(-1);
//                txtNoHp.setText("");
//                txtEmail.setText("");
//     
//    }

    public void tampilDataMahasiswa(){
        try {
           Connection conn = DatabaseConnection.connect();
           String query = "SELECT * FROM mahasiswa";
           PreparedStatement stmt = conn.prepareStatement(query);
           ResultSet rs = stmt.executeQuery();
    
        DefaultTableModel model = new DefaultTableModel(new Object[]{"NIM","Nama","Prodi","Semester","No HP","Email"},0);
    
            while (rs.next()) {                
                model.addRow(new Object[]{
                rs.getString("nim"),
                rs.getString("nama"),
                rs.getString("prodi"),
                rs.getInt("semester"),
                rs.getString("no_hp"),
                rs.getString("email"),
                rs.getDate("created_at")
                });
            }
        tableMahasiswa.setModel(model);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error : "+e.getMessage());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableMahasiswa = new javax.swing.JTable();
        btnTambah = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("FORM MAHASISWA");

        tableMahasiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableMahasiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMahasiswaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableMahasiswa);

        btnTambah.setText("Tambah Data");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        jButton1.setText("Hapus");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnUpdate.setText("Lihat Detail");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 744, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(btnTambah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableMahasiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMahasiswaMouseClicked
        // TODO add your handling code here:

//        int baris = tableMahasiswa.rowAtPoint(evt.getPoint());
//
//        String nim = tableMahasiswa.getValueAt(baris, 0).toString();
//
//        try {
//            Connection conn = DatabaseConnection.connect();
//            String query = "SELECT * FROM mahasiswa WHERE nim =? ";
//            PreparedStatement stmt = conn.prepareStatement(query);
//            stmt.setString(1, nim);
//            ResultSet rs = stmt.executeQuery();
//
//            if (rs.next()) {
//                txtNama.setText(rs.getString("nama"));
//                comboProdi.setSelectedItem(rs.getString("prodi"));
//                comboSemester.setSelectedItem(rs.getString("semester"));
//                txtNoHp.setText(rs.getString("no_hp"));
//                txtEmail.setText(rs.getString("email"));
//            }
//        } catch (SQLException e) {
//            JOptionPane.showMessageDialog(this, "Error : " + e.getMessage());
//        }
    }//GEN-LAST:event_tableMahasiswaMouseClicked

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        
        FormSimpan simpan = new FormSimpan(this, true);
        
         simpan.setLocationRelativeTo(this);
         simpan.setVisible(true);
         tampilDataMahasiswa();
        
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        
        int baris = tableMahasiswa.getSelectedRow();
        
        if (baris == -1) {
            JOptionPane.showMessageDialog(this, "Tidak ada data yang dipilih");
            return;
        }
        
        String nim = tableMahasiswa.getValueAt(baris, 0).toString();
        
        FormEdit edit = new FormEdit(this, true, nim);
        edit.setLocationRelativeTo(this);
        edit.setVisible(true);
        tampilDataMahasiswa();
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        int baris = tableMahasiswa.getSelectedRow();
        
        if (baris == -1) {
            JOptionPane.showMessageDialog(this, "Tidak ada data yang dipilih");
            return;
        }
        
        int confirm = JOptionPane.showConfirmDialog(this, "Anda yakin ingin menghapus data ini ? ", "KONFIRMASI", JOptionPane.YES_NO_OPTION);
        
        if (confirm == JOptionPane.YES_OPTION) {
            try {
                String nim = tableMahasiswa.getValueAt(baris, 0).toString();
                
                Connection conn = DatabaseConnection.connect();
                String deleteUser = "DELETE FROM users  WHERE nim = ?";
                PreparedStatement stmtUser = conn.prepareStatement(deleteUser);
                stmtUser.setString(1,nim);
                int deleteConfirmUser = stmtUser.executeUpdate();
                String deleteMhs = "DELETE FROM mahasiswa WHERE nim = ?";
                PreparedStatement stmtMhs = conn.prepareStatement(deleteMhs);
                stmtMhs.setString(1, nim);
                int deleteConfirmMhs = stmtMhs.executeUpdate();
                

                
                if (deleteConfirmMhs > 0 && deleteConfirmUser > 0) {
                    JOptionPane.showMessageDialog(this, "Berhasil menghapus data");
                    tampilDataMahasiswa();
                }else{
                    JOptionPane.showMessageDialog(this, "Gagal menghapus data NIM tidak ada");
                    return;
                }
                
                
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Error : "+ e.getMessage());
            }
            
        }
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                FormMahasiswa dialog = new FormMahasiswa(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableMahasiswa;
    // End of variables declaration//GEN-END:variables
}
