 /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Mahasiswa.Pengajuan;
import Config.DatabaseConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;



import javax.swing.JOptionPane;

/**
 *
 * @author muhrobby
 */
public class FormPengajuanMagang extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormPengajuanMagang.class.getName());

    private String nimUser, namaUser;
    /**
     * Creates new form FormPengajuanMagang
     */
    public FormPengajuanMagang(java.awt.Frame parent, boolean modal, String nim, String nama) {
        super(parent, modal);
        initComponents();

        this.nimUser = nim;
        this.namaUser = nama;
                tampilPengajuanMagang();
        
//        jTextField1.setEnabled(false);
//        jTextField2.setEnabled(false);
//        jTextField1.setText(nimUser);
//        jTextField2.setText(namaUser);
    }

    public final void tampilPengajuanMagang (){
        try {
           Connection conn = DatabaseConnection.connect();
           String query = "SELECT * FROM pengajuan WHERE nim = ?";
           PreparedStatement stmt = conn.prepareStatement(query);
           stmt.setString(1, nimUser);
           ResultSet rs = stmt.executeQuery();
            
        DefaultTableModel model = new DefaultTableModel(new Object[]{"id","nim","nama","prodi","tempat","alamat", "dosen", "status","created_at"},0);
        
            while (rs.next()) {                
                model.addRow(new Object[]{
                rs.getInt("id"),
                rs.getString("nim"),
                rs.getString("nama"),
                rs.getString("prodi"),
                rs.getString("tempat"),
                rs.getString("alamat"),
                rs.getString("dosen"),
                rs.getString("status"),
                rs.getDate("created_at")
                });
            }
        jTable1.setModel(model);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error : "+e.getMessage());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("PENGAJUAN MAGANG");
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setText("Buat Pengajuan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 716, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        FormTambah formTambah = new FormTambah(this, true, nimUser);
        
        formTambah.setLocationRelativeTo(this);
        formTambah.setVisible(true);
        
        tampilPengajuanMagang();
        
//        String nim = jTextField1.getText();
//        String nama = jTextField2.getText();
//        String prodi = jComboBox1.getSelectedItem().toString();
//        String tempat = jTextField3.getText();
//        String alamat = jTextArea1.getText();
//        String dosen = jTextField4.getText();
//
//        
//        if(nim.isEmpty() || nama.isEmpty() || tempat.isEmpty() || alamat.isEmpty() || dosen.isEmpty()) {
//            JOptionPane.showMessageDialog(this, "Harap lengkapi semua data!", "Error", JOptionPane.ERROR_MESSAGE);
//        }else{
//            try{
//                Connection conn = DatabaseConnection.connect();
//                String sql = "INSERT INTO pengajuan (nim, nama, prodi, tempat, alamat, dosen, status) VALUES (?,?,?,?,?,?,?)";
//                PreparedStatement pst = conn.prepareStatement(sql);
//                pst.setString(1, nim);
//                pst.setString(2, nama);
//                pst.setString(3, prodi);
//                pst.setString(4, tempat);
//                pst.setString(5, alamat);
//                pst.setString(6, dosen);
//                pst.setString(7, "diproses");
//
//                pst.executeUpdate();
//                JOptionPane.showMessageDialog(this, "Data berhasil disimpan!");
//                tampilFormPengajuanMagang();
//            }catch (Exception e) {
//                JOptionPane.showMessageDialog(this, "Gagal menyimpan data: " + e.getMessage());
//            }
//        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                FormPengajuanMagang dialog = new FormPengajuanMagang(new javax.swing.JFrame(), true, null, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
